version: "3.3"
services:
  api:
    depends_on:
      - db
    container_name: todo-api
    build:
      context: ./
      dockerfile: Dockerfile
    image: todo-api
    ports:
      - 8888:8888
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: wBtpCV8N5DvVddyD
      DB_NAME: todo
      DATABASE_URL: "mysql://root:wBtpCV8N5DvVddyD@db:3306/todo?schema=public"
      JWT_TOKEN_SECRET: "]eme!5[~5RkwnM~X"
    links:
      - db
    volumes:
      - ./:/src
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: wBtpCV8N5DvVddyD
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local